# Generated by Django 4.2.7 on 2024-11-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="short_description",
            field=models.CharField(
                default="Des", help_text="A brief one-line description for the card view", max_length=250
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agent",
            name="description",
            field=models.TextField(help_text="Full description for the detail page"),
        ),
    ]
