# Generated by Django 4.2.7 on 2024-11-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_agent_short_description_alter_agent_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="category",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="tags",
        ),
        migrations.AddField(
            model_name="agent",
            name="categories",
            field=models.ManyToManyField(related_name="agents", to="agents.category"),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
