# Generated by Django 4.2.7 on 2024-11-24 04:23
# This migration file is used to seed the database with the legacy data from the legacy_ai_agents.json file (exported from the old website which was running on Notion database).
# It creates the categories and agents, and associates the agents with the categories.

import json
import os
from django.db import migrations
from django.utils.text import slugify
from urllib.parse import urlparse, parse_qs, urlencode, urlunparse

def clean_url(url):
    """Remove tracking parameters from URL"""
    if not url:
        return ''
    
    # Parse URL
    parsed = urlparse(url)
    
    # Get query parameters and remove tracking ones
    query_params = parse_qs(parsed.query)
    cleaned_params = {
        k: v for k, v in query_params.items() 
        if not k.startswith(('utm_', 'ref_', 'source', 'campaign'))
    }
    
    # Rebuild URL without tracking parameters
    cleaned = parsed._replace(
        query=urlencode(cleaned_params, doseq=True)
    )
    
    return urlunparse(cleaned).rstrip('?')  # Remove trailing ? if no params left

def load_legacy_data():
    """Load data from legacy_ai_agents.json file"""
    current_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(current_dir, 'legacy_ai_agents.json')
    
    agents = []
    with open(json_path, 'r') as file:
        for line in file:
            if line.strip():  # Skip empty lines
                agents.append(json.loads(line))
    return agents

def seed_data(apps, schema_editor):
    Category = apps.get_model('agents', 'Category')
    Agent = apps.get_model('agents', 'Agent')
    
    print("\n=== Starting data migration ===")
    
    # Get legacy data
    legacy_agents = load_legacy_data()
    print(f"Loaded {len(legacy_agents)} agents from legacy data")
    
    # Extract unique categories
    categories = set()
    for agent in legacy_agents:
        if agent.get('categories'):
            categories.add(agent['categories'])
    
    print(f"\nFound {len(categories)} unique categories:")
    for cat in sorted(categories):
        print(f"  - {cat}")
    
    # Create categories first
    category_objects = {}
    for cat_name in sorted(categories):
        if cat_name:  # Skip empty categories
            category = Category.objects.create(
                name=cat_name,
                slug=slugify(cat_name)  # Generate slug from name
            )
            category_objects[cat_name] = category
            print(f"Created category: {cat_name} (slug: {category.slug})")
    
    # Create agents and associate categories
    print("\nCreating agents:")
    for agent_data in legacy_agents:
        # Clean website URL
        cleaned_website = clean_url(agent_data['website'])
        if cleaned_website != agent_data['website']:
            print(f"  Cleaned URL for {agent_data['name']}:")
            print(f"    From: {agent_data['website']}")
            print(f"    To:   {cleaned_website}")
        
        agent = Agent.objects.create(
            name=agent_data['name'],
            slug=agent_data['slug'],
            short_description=agent_data['short_description'],
            description=agent_data['short_description'],
            website=cleaned_website
        )
        
        # Add category if exists
        if agent_data.get('categories') and agent_data['categories'] in category_objects:
            agent.categories.add(category_objects[agent_data['categories']])
            print(f"Created agent: {agent.name} (slug: {agent.slug}) in category: {agent_data['categories']}")
        else:
            print(f"Created agent: {agent.name} (slug: {agent.slug}) with no category")
    
    print("\n=== Migration completed successfully ===")

class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_remove_agent_category_remove_agent_tags_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_data, migrations.RunPython.noop),
    ]
