# Generated by Django 4.2.7 on 2024-11-26 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_seed_agents_and_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["-featured", "order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order", "name"], "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="agent",
            name="featured",
            field=models.BooleanField(default=False, help_text="Whether this agent should be highlighted as featured"),
        ),
        migrations.AddField(
            model_name="agent",
            name="order",
            field=models.IntegerField(
                default=1,
                help_text="Order in which items appear (starting from 1, lower numbers first)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(
                default=1,
                help_text="Order in which items appear (starting from 1, lower numbers first)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
