# Generated by Django 4.2.7 on 2024-12-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_alter_agent_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="website",
            field=models.URLField(help_text="The official website URL of the AI agent", max_length=255, unique=True),
        ),
    ]
