# Generated by Django 4.2.7 on 2025-01-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_alter_agent_name_alter_agent_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="demo_video_url",
            field=models.URLField(
                blank=True, help_text="YouTube, Loom, or Vimeo video URL", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of features (e.g., 'API Integration, Custom Training, Multi-language')",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="industry",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("GENERAL", "General Purpose"),
                    ("HEALTHCARE", "Healthcare"),
                    ("FINANCE", "Finance"),
                    ("EDUCATION", "Education"),
                    ("ECOMMERCE", "E-commerce"),
                    ("MARKETING", "Marketing"),
                    ("LEGAL", "Legal"),
                    ("HR", "Human Resources"),
                    ("TECH", "Technology"),
                    ("CUSTOMER_SERVICE", "Customer Service"),
                    ("RESEARCH", "Research"),
                    ("CONTENT", "Content Creation"),
                ],
                default="UNKNOWN",
                help_text="Primary industry or sector this agent serves",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="is_open_source",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether this agent is open source (None = Unknown, True = Yes, False = No)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile/company URL", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="pricing_model",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("FREE", "Free"),
                    ("FREEMIUM", "Freemium"),
                    ("PAID", "Paid"),
                    ("ENTERPRISE", "Enterprise"),
                    ("CONTACT", "Contact for Pricing"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="twitter_url",
            field=models.URLField(blank=True, help_text="Twitter/X profile URL", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="use_cases",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of use cases (e.g., 'Customer Support, Data Analysis, Content Generation')",
            ),
        ),
    ]
