# Generated by Django 4.2.7 on 2025-01-14 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_agent_demo_video_url_agent_features_agent_industry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="features",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="use_cases",
        ),
        migrations.CreateModel(
            name="UseCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="use_case_set", to="agents.agent"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feature_set", to="agents.agent"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
