# Generated by Django 4.2.7 on 2025-01-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_remove_agent_features_remove_agent_use_cases_usecase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="is_open_source",
            field=models.BooleanField(
                blank=True,
                help_text="Whether this agent is open source (None = Unknown, True = Yes, False = No)",
                null=True,
            ),
        ),
    ]
