# Generated by Django 4.2.7 on 2025-01-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_alter_agent_is_open_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PUBLISHED",
                help_text="Agent visibility status",
                max_length=20,
            ),
        ),
    ]
