# Generated by Django 4.2.7 on 2025-12-25 00:28

import aiagents_directory.agents.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0013_agentsubmission_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsubmission",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Downloaded logo from enrichment (Firecrawl URLs expire in 24h)",
                null=True,
                upload_to=aiagents_directory.agents.models.get_submission_logo_path,
            ),
        ),
        migrations.AddField(
            model_name="agentsubmission",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Downloaded screenshot from enrichment (Firecrawl URLs expire in 24h)",
                null=True,
                upload_to=aiagents_directory.agents.models.get_submission_screenshot_path,
            ),
        ),
        migrations.AlterField(
            model_name="agentsubmission",
            name="ai_review_result",
            field=models.JSONField(blank=True, help_text="Results from AI review (ReviewResult as JSON)", null=True),
        ),
    ]
