# Generated by Django 4.2.7 on 2025-12-25 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0014_add_submission_media_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="order",
            field=models.IntegerField(
                default=10,
                help_text="Order in which items appear (starting from 1, lower numbers first)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
