# Generated by Django 4.2.7 on 2026-01-10 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsFetchRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("articles_found", models.IntegerField(default=0)),
                ("articles_created", models.IntegerField(default=0)),
                ("articles_skipped", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("queries_used", models.JSONField(default=list, help_text="List of search queries used in this run")),
                (
                    "tbs_filter",
                    models.CharField(
                        blank=True, help_text="Time-based search filter used (e.g., qdr:d)", max_length=50
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True, max_length=2000)),
                ("url", models.URLField(max_length=2000, unique=True)),
                ("source_domain", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(help_text="Article's publish date (from source)")),
                ("scraped_at", models.DateTimeField(auto_now_add=True, help_text="When we discovered this article")),
                (
                    "search_query",
                    models.CharField(blank=True, help_text="The search query that found this article", max_length=255),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(fields=["-published_at"], name="news_newsar_publish_db2481_idx"),
                    models.Index(fields=["source_domain"], name="news_newsar_source__a7b719_idx"),
                ],
            },
        ),
    ]
