# Generated by Django 4.2.7 on 2025-01-15 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agents", "0009_alter_agent_is_open_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL to be researched. This is the URL of the agent's website.", max_length=500
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error details if task failed", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "extracted_data",
                    models.JSONField(blank=True, help_text="Extracted data from the research task", null=True),
                ),
                (
                    "previous_data",
                    models.JSONField(blank=True, help_text="Agent data before the research task", null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, help_text="Admin notes during review", null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="research_tasks", to="agents.agent"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="auto_direct_status_961cb6_idx"),
                    models.Index(fields=["agent", "status"], name="auto_direct_agent_i_9ddb52_idx"),
                ],
            },
        ),
    ]
